# NOTE: Gathering CA certicates from alpine BASE image
FROM alpine:3 as alpine-ca
RUN apk add --no-cache ca-certificates

FROM scratch
COPY --from=alpine-ca \
    /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

COPY supernova /usr/bin/supernova
ENTRYPOINT [ "/usr/bin/supernova" ]
