name: Dagger Supernova

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' 

jobs:
  supernova:
    name: supernova-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Dagger version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@v0.0.2
        with:
          path: ci/dagger/run-supernova/
      
      - name: Supernova Run
        uses: dagger/dagger-for-github@v7
        env:
          RPC_URL: https://rpc.gno.land
          CHAIN_ID: staging
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          module: ci/dagger/run-supernova/
          args: run-stress-test --src-dir . --chain-id ${CHAIN_ID} --rpc-endpoint ${RPC_URL} --sub-accounts 2 --transactions 10
