name: Dagger Supernova

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' 
  push:
    branches:
      - fix/linter6

jobs:
  supernova:
    name: supernova-ci
    runs-on: ubuntu-latest
    # runs-on: [ self-hosted, Linux, X64, dagger ]
    strategy:
      matrix:
        env: [PACKAGE_DEPLOYMENT, REALM_DEPLOYMENT, REALM_CALL]
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Dagger version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@v0.0.2
        with:
          path: ci/dagger/run-supernova/
      
      - name: Supernova Run
        uses: dagger/dagger-for-github@v7
        env:
          RPC_URL: https://rpc.gno.land
          CHAIN_ID: staging
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          module: ci/dagger/run-supernova/
          args: run-stress-test --src-dir . --chain-id ${CHAIN_ID} --rpc-endpoint ${RPC_URL} --mode ${{ matrix.env }} --sub-accounts 2
