name: dagger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

  supernova:
    name: supernova-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Supernova Run
        uses: dagger/dagger-for-github@v7
        env:
          RPC_URL: https://rpc.test4.gno.land/
          CHAIN_ID: test4
        with:
          version: "v0.15.2"
          verb: call
          workdir: ci/dagger
          args: run-stress-test --src-dir . --chain-id ${CHAIN_ID} --rpc-endpoint ${RPC_URL} --sub-accounts 2 --transactions 10
