name: Lint Go Code

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v1.63
