name: Lint Go Code

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - fix/linter6

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --timeout=5m
