name: Main Branch - Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  lint:
    name: Go Linter
    uses: ./.github/workflows/lint.yaml

  test:
    name: Go Test
    uses: ./.github/workflows/test.yaml
