name: Go Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Go test
        run: go test -shuffle=on -coverprofile coverage.out -timeout 5m ./...

  test-with-race:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Go race test
        run: go test -race -shuffle=on -timeout 5m ./...
